name: Promote

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags (Optional)'
        default: 'prod'
  push:
    branches:
      - 'releases/*.*.*'
      - '!releases/*_*.*.*'

jobs:
  promote:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
        # If the version has changed, create a new git tag for it.
      - name: Identify Version
        id: identify
        run: | 
          echo ${{ env.GITHUB_REF}} released.
     
